Repository AY2122S1-CS2103-F09-2/tp, pull requests merged in 2021-11, with the labels that each got.

#133 Bug fix: DoneTaskCommand undo/redo
  src/main/java/seedu/address/logic/commands/task/DoneTaskCommand.java
Labels: type.Bug, priority.High, severity.High

#140 Change timestamp UG, format
  docs/UserGuide.md
  src/main/java/seedu/address/model/task/Timestamp.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: type.Bug, priority.Medium

#187 Add sample tasks
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low

#197 Prevent overlap of task title and checkbox, set min length of task panel
  build.gradle
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: type.Bug, priority.Medium, severity.Low

#204 Update PPP and edit DG
  docs/DeveloperGuide.md
  docs/team/jeffsieu.md
  docs/team/mingyi456.md
Labels: priority.High, documentation

#206 Update, Fix diagrams
  docs/diagrams/EditTaskCommandParse.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/EditTaskCommandParse.png
  docs/images/ModelClassDiagram.png
Labels: documentation
